# Generated by Django 3.0.3 on 2020-02-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('exercise_type', models.CharField(choices=[('S', 'Strength'), ('A', 'Aerobic')], max_length=3)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('repetitions', models.PositiveIntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exercise', models.ManyToManyField(blank=True, null=True, related_name='workout_exercises', to='activity.Exercise')),
            ],
        ),
    ]
